### ISSUE TITLE
Some combos no longer work and do not advance their steps

### ISSUE THREAD

**Issue by CoryInUrHouse** [attickdoor/XIVComboPlugin#10]
Things found which won't advance thus far:

GNB Gnashing Fang combo
All of SMN tabs
Both BLM tabs
NIN Hakke Mujinsatsu combo
MCH Hypercharge to heat shot, spread shot to crossbow
Both SCH tabs

Everything else is either fine and working or I'm unable to test them personally. Hope this helps!

**Comment by attickdoor** [comment]
Things that aren't working due to job gauge data will be rectified soon. That matter is out of my hands, but I've PRed the necessary info.

The other stuff is probably fixed by re-downloading the latest version. Some data moved when I thought it hadn't, so things that upgraded based on your level were often broken. It's correct now.

**Comment by attickdoor** [comment]
This has been fixed. Make sure everything's up to date.
