### ISSUE TITLE
BLM Request Fire/Ice "Combo" Buttons

### ISSUE THREAD

**Issue by alexankitty** [attickdoor/XIVComboPlugin#11]
Merging of Fire with Blizzard (vice versa) and Blizzard II with Fire II,.
In my experience these abilities will generally only be in their respective astral and umbral states (and most people start off in fire anyway)

**Comment by attickdoor** [comment]
They do seem pretty exclusive...this isn't true until level 4 when you learn transpose, but that's 3 levels where you probably aren't doing combat anyways. I'll consider it, it seems pretty in line. But for what it's worth, B3 and F3 will never get merged because there's too much logic surrounding which one to use. Not cut and dry at all. In a similar vein, B2 can't upgrade into Freeze because the new Freeze has B3-like properties.

**Comment by alexankitty** [comment]
Yeah, I think the first two tiers are fine, the rest don't really seem worth it. Plus the first 3 levels thing even if you are fighting can just be remedied by disabling in settings.
