### ISSUE TITLE
SMN Ability Suggestion

### ISSUE THREAD

**Issue by chordlessmelody** [attickdoor/XIVComboPlugin#114]
Gemshine/Precious Brilliance over Ruin/Tri-Disaster when in Ruby/Topaz/Emerald phases

**Comment by attickdoor** [comment]
maybe.

**Comment by kaw-kaw** [comment]
Would also appreciate this one a lot.

**Comment by Mete0** [comment]
+1

**Comment by dixiebe** [comment]
7 buttons down to 5 buttons.
Yes it would work extremely well, but the question is... How easy do we want summoner to be.. its already braindead.

**Comment by Kylis** [comment]
Yeah we never want to use ruin or tri-disaster while we have stacks of fire/earth/wind attunement, so this would work exceptionally well.

**Comment by chordlessmelody** [comment]
> 7 buttons down to 5 buttons. Yes it would work extremely well, but the question is... How easy do we want summoner to be.. its already braindead.

yeah i agree, but in all honesty those buttons are a redundancy - they're the literal exact same abilities with new names, it doesn't make any sense to have them be separate

i just think summoner needs more _different_ buttons to press rather than redundant ones like those

**Comment by Roman215** [comment]
+1 as I was thinking of having this as well. Along the same lines it would make sense to have Further Ruin Ruin IV be on the same button in a priority order. Highest priority is Astral Impulse/Gemshine, then Further Ruin Ruin IV. So same button is Astral Impulse with Dreadwyrm Trance, Gemshine when in primal phases, Ruin IV when procced, and finally Ruin III. Since all those buttons serve the same exact purpose you would think this makes sense.

**Comment by attickdoor** [comment]
"Maybe" is actually "no". You need to cast at least one Ruin per minute or some such. There is absolutely no rule that says you aren't allowed to do it when attuned to a primal, and there may be very valid reasons to do so. At best, I might consider distributing Gemshine across each of the Summon Primal buttons, but certainly not over Ruin.
