### ISSUE TITLE
[Suggestion] Raise becomes Swiftcast -> Raise

### ISSUE THREAD

**Issue by MidoriKami** [attickdoor/XIVComboPlugin#115]
Option for various resurrections to start as swiftcast.

This would allow a lot of healers / rezmages / summoners to not need a macro or multiple macros to rez players.

**Comment by arrek85** [comment]
Thought the use of the macros was more for targeting purposes so you don't raise the same person, which shouldn't be a thing anymore with target number showing in the party list.

Wouldn't say no to having this tho as an option but it wouldn't save me any space since I would still want SC for other cast options at times.

**Comment by MidoriKami** [comment]
A lot of people macro:
/ac "swiftcast"
/ac "raise" <t>

With a XIVCombo you would simply use the button twice, first to activate swiftcast, wait the 700ms for animation lock, then trigger raise.

The current issue with Raise Macros is it is really easy to cancel the raise action after using swiftcast.

With XIVCombo the raise action would get queued by the game like a normal skill action.

**Comment by attickdoor** [comment]
no.
