### ISSUE TITLE
[BLM] Transpose -> Umbral Soul is backwards

### ISSUE THREAD

**Issue by plug-ffxiv** [attickdoor/XIVComboPlugin#155]
Currently, the option is to replace Transpose -> Umbral Soul when Umbral Ice is active. But this makes Transpose unusable to switch Umbral Ice -> Astral Fire, which is the recommended way of switching if you have a Firestarter proc and can use Paradox in Umbral Ice to weave (for example).

It would be better to replace Umbral Soul -> Transpose in Astral Fire, because this would give you exactly the same functionality as the current implementation without precluding regular Transpose usage.

I can make a pull request with the fix if it helps.

**Comment by attickdoor** [comment]
Actually, this is an argument for removing the combo. That said, I don't ascribe to dumb BLM rotation memes (although I do understand that an AF1 F3P to end UI is more valuable than a mid-AF3 F3P). So probably I'll be taking it out soon. Thanks!

**Comment by GermanOrtega** [comment]
Many of us do this:

"Transpose can be used when ending uptime phases in Astral Fire in order to use Umbral Soul during downtime or as a last resort with low Astral Fire timer to prevent dropping Enochian."

As explained [here ](https://www.icy-veins.com/ffxiv/black-mage-pve-dps-rotation-openers-abilities), and so, regardless of there being a better option it would still be great to have this option back (even if not optimal) for how convenient is to quickly transpose when no target is active to use some Blizzard spell and then keep using Umbral Ice to avoid losing enochian.
