### ISSUE TITLE
[suggestion] Summon I & II >  Gemshine 

### ISSUE THREAD

**Issue by piastol** [attickdoor/XIVComboPlugin#160]
What is thy suggestion?
[You should probably type that here]
Summon Ifrit I >  Gemshine 
Summon Ifrit II >  Gemshine 
Summon Titan I >  Gemshine 
Summon Titan I >  Gemshine 
Summon Garuda I >  Gemshine 
Summon Garuda II >  Gemshine 

1) Are abilities in question must be truly mutually exclusive?
yes
2) Does this actually saves you button space?
yes
3) Is it wild and wacky?
no
4) Is the overall level of intelligence required to execute is about as low as the floor?
yes

**Comment by BetrayingBadger** [comment]
The other option for this would be to go which in my opinion is better due to it covering both aoe and single target is: 

Ruin  > Gemshine when a gem is active 
Outburst > Precious brilliance when a gem is active 

The summoners base ruin is just replaced as it levels up the same with their outburst becoming tri-disaster

They are not mutually exclusive but it saves button space. But its essentially the summoner combo and at no time should you be hard casting a base ruin when you have gems so they might as well be. 

This change seems very in line with the other changes in the plugin and not wild or wacky. It is technically achievable via a macro and this is how i personally play summoner BUT this plugins solution is so much better

**Comment by Kroxywuff** [comment]
I second changing Ruin into Gemshine and Tri-Disaster into Precious Brilliance when the gems are active. It should be this way be default but they decided to make it 2 different spells.

**Comment by Baelrayne** [comment]
3rd'ed

**Comment by CMDRNuffin** [comment]
You can use base ruin to quickly kill the last add and save the stronger gem cast (especially if it's Ruby Rite which takes _ages_) for the main boss.

**Comment by attickdoor** [comment]
how are so many people hurting for button space on smn?
