### ISSUE TITLE
[suggestion] Summoner -- Bahamut/Pheonix into enkindle while active

### ISSUE THREAD

**Issue by BetrayingBadger** [attickdoor/XIVComboPlugin#162]
What is thy suggestion?
My suggestion would be to be for summoner to change Summon Bahamut into Enkindle Bahamut

Summon Bahamut > Enkindle Bahamut while bahamut is active

The game automatically shifts them to phoenix phase but if necessary, 

Summon Phoenix > Enkindle Phoenix While it is active

1) Are abilities in question must be truly mutually exclusive?
yes they are mutually exclusive. You cannot enkindle without bahamut/phoenix active 

2) Does this actually saves you button space?
Yes 

3) Is it wild and wacky?
This seems in line with other changes. Its acheivable through a macro but I figured it would be better to suggest it to the forum

4) Is the overall level of intelligence required to execute is about as low as the floor?
Yes it is in line with what the plugin already does and should be very simple to execute.

**Comment by CMDRNuffin** [comment]
You only save buttons if you also replace the elemental summon buttons with enkindle if their respective summons are out, because once you are level 90, they also grant Enkindle abilities.

Note that replacing bahamut with enkindle while another egi is out doesn't work because you might want to immediately replace the elemental egi with bahamut.
