### ISSUE TITLE
[BLM][suggestion] Transpore/Umbral Soul

### ISSUE THREAD

**Issue by tlecas** [attickdoor/XIVComboPlugin#192]
What is thy suggestion?
Remove this option or indicate in the description that it's suboptimal. This option doesn't meet the current requirements for suggestions.

1) Are abilities in question truly mutually exclusive?
They are not, non-standard lines rely on having access to Transpose while in UI. It's also required to use Firestarter procs efficiently in the standard rotation (which doesn't require additional ressources in EW with Paradox granting a consistent instant spell every UI phase).

**Comment by PlumIceFox** [comment]
If one wants to still save one button, then we could introduce a switch between Umbral Soul and Despair depending on the UI/AF stance excatly like how it works for Blizzard IV/Fire IV and Freeze/Flare.

Of course Umbral Soul and Despair have complete different purposes but still, since they are only available on their correct stance, and Despair is learnt earlier, it makes sense to change it into Umbral Soul when in UI.

**Comment by BetrayingBadger** [comment]
Im personally for more options rather than less options. If you dont want to use it, then leave it turned off.

**Comment by attickdoor** [comment]
> Im personally for more options rather than less options. If you dont want to use it, then leave it turned off.

in that case, I'll implement a perfect rotation bot, and you can turn it off if you don't want to use it.

honestly I hadn't considered umbral soul and despair. that just might work...
