### ISSUE TITLE
Transpose into Umbral Ice

### ISSUE THREAD

**Issue by The-Letter-X** [attickdoor/XIVComboPlugin#217]
Transition appears to be nonfunctional and missing from the menu. Has it been removed?
![2022-04-16 11_46_29-FINAL FANTASY XIV](https://user-images.githubusercontent.com/68640840/163681685-b9530ccb-4caf-4541-afc1-67e4cf23c6a5.png)

**Comment by Xelfen** [comment]
the reason ... : https://github.com/attickdoor/XIVComboPlugin/issues/155

**Comment by GermanOrtega** [comment]
Many of us do this:

"Transpose can be used when ending uptime phases in Astral Fire in order to use Umbral Soul during downtime or as a last resort with low Astral Fire timer to prevent dropping Enochian."

As explained [here ](https://www.icy-veins.com/ffxiv/black-mage-pve-dps-rotation-openers-abilities), and so, regardless of there being a better option it would still be great to have this option back (even if not optimal) for how convenient is to quickly transpose when no target is active to use some Blizzard spell and then keep using Umbral Ice to avoid losing enochian.

**Comment by attickdoor** [comment]
no
