### ISSUE TITLE
Where is the maintained version?

### ISSUE THREAD

**Issue by Draiven123** [attickdoor/XIVComboPlugin#282]
Where is the maintained version?

**Comment by xivTaru** [comment]
Look at the forks, there is a working version with functionality that is really close to this version

**Comment by Lightningcount** [comment]
How do you apply it?

**Comment by rodrigo-gutierrez** [comment]
The last line of the README.md explains it

**Comment by Draiven123** [comment]
> The last line of the README.md explains it

"None, for now!" ?

**Comment by xivTaru** [comment]
Look at the most recently updated one

**Comment by Jyabil** [comment]
Looking at the most recent updated one still has the same readme as the master.

**Comment by xivTaru** [comment]
Oh brother... Are you looking at the one by MKhayle? There's an extra line at the bottom

**Comment by KumaBurr** [comment]
Well which one is it by that youre looking at

**Comment by syncmaster255** [comment]
> Look at the forks, there is a working version with functionality that is really close to this version

explain for a stupid idiot like me

**Comment by syncmaster255** [comment]
> Oh brother... Are you looking at the one by MKhayle? There's an extra line at the bottom

Do I just paste the address in the settings or is there something I need to do?

**Comment by lovelydumpling** [comment]
I've checked out that version, it's... got a LOT of extra combos that would never be allowed in base XIVCombo.

I kinda prefer the standards in place by base XIVCombo so I do hope it gets updated soon.

**Comment by xivTaru** [comment]
> I've checked out that version, it's... got a LOT of extra combos that would never be allowed in base XIVCombo.
> 
> I kinda prefer the standards in place by base XIVCombo so I do hope it gets updated soon.

I 100% agree

**Comment by IndigoVagrant** [comment]
The expanded version is here
https://github.com/MKhayle/XIVComboPlugin/tree/master

**Comment by IndigoVagrant** [comment]
Can someone just post a link to the directory for the new one? I a lot of us don't understand this platform, forks and all that.  I've used it a bit at a job, but I'm no programmer.

**Comment by JohnnyMedieval** [comment]
Can someone please explain a "for dummies" step by step instructions to get the maintained version of XIV Combo working for average users like me, who don't know any programming or anything and just installed the XIV launcher and Dalamud with the Setup.exe installer and installed plugins in-game thorough Dalamud?

**Comment by LillyAviona** [comment]
Is there a maintained fork that is not the "expanded" one? I don't like a lot of the extra features it throws in there, they feel a bit sketch to me.

I saw one by AltinaXIV, but the repo they have doesn't seem to actually show up when added to Dalamud.

**Comment by JohnnyMedieval** [comment]
"Place https://github.com/daemitus/MyDalamudPlugins/raw/master/pluginmaster.json in your /xlsettings 3rd party repo list to access this plugin."  For example, this doesn't mean anything to a user who installed with Setup.exe and hasn't done anything with files.

**Comment by IndigoVagrant** [comment]
I'm letting the mod creator know people are need of step by step instruction, linking them here.

In Dalamud Settings (accessed in game via /xldev), you go to the "Experimental" tab.  Users of Penumbra will be familiar with this tab. 

First on this tab, enable "Get Plugin Testing Builds"

Then scroll down, go to "Custom Plugin Repositories"
Enter this on an empty line 
https://github.com/daemitus/MyDalamudPlugins/raw/master/pluginmaster.json
Then hit the + button and the Save Changes and Close icon nearby

Close out the screen.
At the top of your screen, the Dalamud bar should still be present. Use /xldev again if it is not.
Go to Plugins. Open the Plugin Installer(also accessible from the Title Screen).  You should now be able to search the plugin.

 Type XIV Combo Expanded or just "Combo". You will see "XIV Combo Expanded" in the list.  Install it.

Make sure you deleted your old XIV Combo plugin first. You will have to do new settings for this one. It is more detailed, and way procs are activated(like on Dancer) is a bit different(you will use the base skill instead of the procced version on your hotbar to make it work).  Just read the options carefully before activating them and you will figure it out.

I just spent about 2 hours testing with plugin and I am highly satisfied with it over the old one.  It is really good. I would suggest enabling "Secret Forbidden Knowledge". It simply gives you more options(shown with green stars next to them)


![Capture](https://github.com/attickdoor/XIVComboPlugin/assets/147122098/5616b37f-aa5e-43aa-a7eb-6c31ce913373)

**Comment by IndigoVagrant** [comment]
![Capture](https://github.com/attickdoor/XIVComboPlugin/assets/147122098/cc7c70e4-0990-46cb-8ee1-1c24064ce231)

**Comment by lovelydumpling** [comment]
For the record y'all, this version is still being maintained. It's just not updated yet. If you wait it will be updated.

**Comment by JohnnyMedieval** [comment]
Thanks for the directions, I got it working.

**Comment by JohnnyMedieval** [comment]
Thanks for the directions @IndigoVagrant , I got it working.

**Comment by ExtraThicc1993** [comment]
You are doing god's work, thank you so much for taking care of this when the author of the regular plugin wouldn't

**Comment by lovelydumpling** [comment]
I feel like that's kind of rude. You have no idea what's going on in their life, just because they didn't hop to it and have it ready right away by Dalamud's return doesn't mean they aren't working on it. 

Plus again Khayle's isn't the same plugin, it's a fork that's meant to expand it with options that are considered too cheaty for the default Dalamud plugin repository. The goals there are a bit different and it's not a replacement for the original.

**Comment by IndigoVagrant** [comment]
> You are doing god's work, thank you so much for taking care of this when the author of the regular plugin wouldn't

To be fair, the update was quite recent.
Both mods are good.  The original(being updated now) is more straightforward and probably better for people who don't want to think too much about the mod or change their playstyle as much.  The fork is good for people who like to spend a lot of time tweaking to optimize.

**Comment by Astral-Crescent** [comment]
> I feel like that's kind of rude. You have no idea what's going on in their life, just because they didn't hop to it and have it ready right away by Dalamud's return doesn't mean they aren't working on it.
> 
> Plus again Khayle's isn't the same plugin, it's a fork that's meant to expand it with options that are considered too cheaty for the default Dalamud plugin repository. The goals there are a bit different and it's not a replacement for the original. They just happened to be able to update theirs faster than attick could.

Bruh, disabled people exist. Humble yourself.

**Comment by lovelydumpling** [comment]
Not only did I say absolutely nothing of the sort but I'm also disabled myself and that's also why I use XIVCombo.

All I said was that XIVCombo and XIVCombo Extended are not the same plugin and to be mindful of the people who put in the free labor for the mods you enjoy and that they have lives too and just because they don't get to it right away doesn't mean they've abandoned the project.

**Comment by lyndistt** [comment]
> > I feel like that's kind of rude. You have no idea what's going on in their life, just because they didn't hop to it and have it ready right away by Dalamud's return doesn't mean they aren't working on it.
> > Plus again Khayle's isn't the same plugin, it's a fork that's meant to expand it with options that are considered too cheaty for the default Dalamud plugin repository. The goals there are a bit different and it's not a replacement for the original. They just happened to be able to update theirs faster than attick could.
> 
> Bruh, disabled people exist. Humble yourself. This game is LITERALLY UNPLAYABLE for me with my disabilities without this mod and ones like it. Several days of subscription that I am PAYING FOR when I am in debt and poverty that I can physically not play this game are unreasonable. Just because people need help doesn't mean you have the right to be a Dick.
> 
> "HUR HUR I HATE CHEATY" players are literally a cancer because you are Ableist by Default.

I made an account just for this.
Wtf is this entitlement? 💀💀
Just skill issue tbh xd

**Comment by stuffinhere** [comment]
> Bruh, disabled people exist. Humble yourself. This game is LITERALLY UNPLAYABLE for me with my disabilities without this mod and ones like it. Several days of subscription that I am PAYING FOR when I am in debt and poverty that I can physically not play this game are unreasonable. Just because people need help doesn't mean you have the right to be a Dick.
> 
> "HUR HUR I HATE CHEATY" players are literally a cancer because you are Ableist by Default.

The harsh truth is that absolutely no one has to care about you or your conditions, much less modders who make mods in their free time. 
Using your supposed "disability" as an excuse to be rude and throw insults around? That tells me you're not really disabled, just tossing around "cards".

If you're so poor and in debt, that you're annoyed at losing some play days (which, on the 13€ sub amounts to a grand 4c A DAY), then you shouldn't be paying for a game sub in the first place. 

Take your hatred and rudeness somewhere else.

**Comment by devmpg** [comment]
> > I feel like that's kind of rude. You have no idea what's going on in their life, just because they didn't hop to it and have it ready right away by Dalamud's return doesn't mean they aren't working on it.
> > Plus again Khayle's isn't the same plugin, it's a fork that's meant to expand it with options that are considered too cheaty for the default Dalamud plugin repository. The goals there are a bit different and it's not a replacement for the original. They just happened to be able to update theirs faster than attick could.
> 
> Bruh, disabled people exist. Humble yourself. This game is LITERALLY UNPLAYABLE for me with my disabilities without this mod and ones like it. Several days of subscription that I am PAYING FOR when I am in debt and poverty that I can physically not play this game are unreasonable. Just because people need help doesn't mean you have the right to be a Dick.
> 
> "HUR HUR I HATE CHEATY" players are literally a cancer because you are Ableist by Default.

Internet discourse really died the day people like you learned the word "ableist".

**Comment by attickdoor** [comment]
> Where is the maintained version?

this is the maintained version. i'm working on updating it. thanks for the kind words everyone!

**Comment by Rhyme** [comment]
> Bruh, disabled people exist. Humble yourself. This game is LITERALLY UNPLAYABLE for me with my disabilities without this mod and ones like it. Several days of subscription that I am PAYING FOR when I am in debt and poverty that I can physically not play this game are unreasonable. Just because people need help doesn't mean you have the right to be a Dick.

You aren't paying a sub to the dev of this plugin. Or Dalamud. Or anything you're complaining about.
