### ISSUE TITLE
[suggestion] MNK's single-target can be comboed now

### ISSUE THREAD

**Issue by attickdoor** [attickdoor/XIVComboPlugin#307]
What is thy suggestion?
Now that MNK's combos are based on gauge values, it can be genuinely logicked that "there's no reason to press x when y is more potency". You can see this when using perfect balance with some number of stacks. The game knows which ability to recommend to you.

1) Are abilities in question must be truly mutually exclusive?
For a given definition of "truly", yes.

2) Does this actually saves you button space?
3 buttons.

3) Is it wild and wacky?
Only in the context of my previous statements about MNK.

4) Is the overall level of intelligence required to execute is about as low as the floor?
They literally give you ants for which MNK ability to use now. That's about as braindead as you can get.

Chat, what do we think about this?

**Comment by Skooz** [comment]
I was actually going to work on implementing this, as soon as the Dalamud API had updated gauge info.

There's really no reason *not* to do it. The job's braindead simple, and while you would be eliminating points of failure with this option, you can do that by just staring at your hotbar and hitting the glowing button.

Part of me doesn't really like it, but it is what it is. This is the job now, lol.

**Comment by demonsdawn** [comment]
Sounds like this new rotation is about on par with DNC in difficulty if its truly just "click the glowing button".
that said, go for it.

**Comment by 2Luna** [comment]
I understand your argument and find it convincing. Here are my thoughts:

1. **Logic and Consistency**: Your reasoning that there's no point in using a lower potency ability when the game already tells you the best ability to use is absolutely valid. Consolidating such abilities makes gameplay more efficient and intuitive.

2. **Button Reduction**: Saving three button slots is a significant advantage, especially in a game like FFXIV where many players struggle with the number of abilities and keybindings. Fewer buttons mean a cleaner action bar and more room for new abilities, which could make the game more interesting.

3. **Accessibility and Simplicity**: Since the game already gives you hints on which ability to use next, consolidating these abilities would make the game more accessible for new players. It could also help experienced players focus on the core gameplay and improve their overall experience.

4. **Balance and Gameplay**: Any changes need to be carefully considered to avoid disrupting game balance. However, your suggestions seem well thought out and could serve as inspiration for future official updates.

Overall, I find your proposal reasonable and well-considered. It shows that you genuinely love the game and want to enhance it. Your changes could make the experience more enjoyable and accessible for many players without oversimplifying the game or diminishing its appeal. I think the community could benefit from such improvements, and it would be interesting to see how the developers respond.

**Comment by WiiTee** [comment]
Rather than it being about consistency, logic, button reduction and what not.

I would put it like this. Does this significantly reduce the chance of injury to the hand? If yes, then yes - it is a good idea.

**Comment by MrZeyami** [comment]
Squeenix really needs to stop slapping conditionally-glowy linear progression boxes on my job bars.

**Comment by attickdoor** [comment]
Here's my follow-up thought: Is there ever a reason to use a Fury-granting move when you're not empty on Fury? I think the answer is no. If such is the case, it's a compelling argument to combo them. If there are situations where it might still be useful to use a Fury-granting move, this would be a no-go. But I don't think that's ever the case now.

**Comment by Skooz** [comment]
> Is there ever a reason to use a Fury-granting move when you're not empty on Fury?

There would be two _potential_ reasons:

1. **Positionals.** Alas, it's always better to use Snap Punch (flank) over Demolish (rear), even if you're at the rear instead of the flank; Demolish rear potency is 380, Snap Punch non-flank potency is 420. If you have a fury charge for Snap Punch, there is no reason to use Demolish. 

2. The ol' meme Dragon Kick rotation, which is no longer a thing. While it was proven to be worse even while it had potential, it's not even a question anymore since they nerfed its potency. 

Can't think of anything else...

**Comment by attickdoor** [comment]
Merged with #310
