### ISSUE TITLE
RDM Ver Proc

### ISSUE THREAD

**Issue by Lanselotto** [attickdoor/XIVComboPlugin#39]
it would be better if "verfire" and "verstone" replaced "verthunder" and "veraero" on proc, like in pvp

**Comment by Carighan** [comment]
But as far as how they are used goes, they replace Jolt as the "opener", instead of aero/thunder as the "finisher".

**Comment by Nikslg** [comment]
Saw this topic earlier (since this situation actually brought me to the plugin in the first place) and thought of a way, but I am not sure if it's possible.

Basically merging two options that we currently have as an alternative.

So as of right now we have:
Jolt into Verfire, and Verthunder 2 turning into Impact(Scatter)
My suggestion is an alternative system, which might be impossible, just seemed like other jobs have some part of it.
2 keys (dragged verfire and verstone).
1st cast, means both are jolts.
2nd cast, 1 is verthunder, 1 is veraero.
right now it's similar to what we have in PVP just with jolts.
Now, it procs. one gets replaces with verfire or verstone.
3rd proc, jolt or verfire/stone.
4th changes both skills to verthunder, veraero.
repeat

Bunch of "if"s I know, but if it is possible, then we have full RDM proc rotation in 2 keys.

**Comment by attickdoor** [comment]
> Bunch of "if"s I know, but if it is possible, then we have full RDM proc rotation in 2 keys.
This was once implemented (at least privately), and I removed it for this exact reason. Too much intelligence.

**Comment by NarutoRoll** [comment]
@attickdoor Did you have it working before killing off that branch or were there too many issues with the order of operations?  I was trying to see if the 1, 2, 3 combo was ever fully done for RDM on this plugin or if it was even possible/wanted.  This seemed like another replacement when Dualcast/Acceleration is available.  This _**seems**_ like an easy addition but it might violate the principles you made for this plugin.

Ex:
                
```
if (actionID == RDM.Verstone)
                {
                    if (level >= 80 && (lastMove == RDM.Verflare || lastMove == RDM.Verholy)) return RDM.Scorch;
                    if (level >= 90 && lastMove == RDM.Scorch) return RDM.Resolution;

                    if (SearchBuffArray(167) || SearchBuffArray(1249) || SearchBuffArray(1238))
                    {
                        if (level >= 82) return RDM.Verthunder3;
                        return RDM.Verthunder;
                    }

                    if (SearchBuffArray(1235)) return RDM.Verstone;

                    if (level < 62) return RDM.Jolt;
                    return RDM.Jolt2;
                }
```

**Comment by red-star-fighter** [comment]
> > Bunch of "if"s I know, but if it is possible, then we have full RDM proc rotation in 2 keys.
> 
> This was once implemented (at least privately), and I removed it for this exact reason. Too much intelligence.

Maybe you could "dumb" this down by making it a three key combo instead of 2 as a mutually exclusive option. Simply replace verstone/verfire with veraero/verthunder. It simplifies the combo in the exact same way the AOE combo works while still keeping the base jolt separate, so it's not as simple as pressing two buttons over and over.

**Comment by Carighan** [comment]
But right now it is factually a four key combo, and two of those are usually the same ability (Jolt). This also adds symmetry, which is an important part of how it works as a mental model. 

Note that the big differentiation between the PvE and the PvP side here would be that in PvP, Red Mage has no procs. It's just a 1->2 cast combo for each element. In PvE, it's also 1->2, but can also be 3->2. If we were to do what you say, then it'd be weird:

Say you got Jolt on 1, Veraero on 2 and Verthunder on 3. With your system, your normal cast is either 1->2 or 1->3 if you have no proc, or 2->2 respectively 3->3 if you got one.
