### ISSUE TITLE
AST auto play cards

### ISSUE THREAD

**Issue by UmbraVenus** [attickdoor/XIVComboPlugin#48]
I am thinking if we can do something like:
if dps and dps already not having a card:
--if arrow, balance or spear or lord of crown:
----if melee dps:
------give to the highest enmity melee dps
----else:
------give it to the highest enmity dps
--else:
----if ranged dps:
------give it to the highest ranged dps
----else:
------give it to the highest enmity dps
else:
 --give it to the highest enmity player

I have never done a pull request before, let me know if you'd rather me working on a pull request instead, i think this will really help those playing ast on a controller with the regular weaving card issue, and this is probably the best way to optimize AST game play. 

And if you'd rather like me to work on a pull request, can you tell me which document to fork and edit and which are some sample? Thanks!

**Comment by lucianhatlemauri01** [comment]
First I'd like to say, AST cards aren't given to highest enmity DPS but to those who have their burst window the moment you draw them. It's useless to give a melee card to a Samurai who isn't in his burst, even though it might be at the top of the DPS list. Ninja has one of the highest DPS openers, yet it doesn't mean it's going to be at the top of the DPS list at the end of the encounter.

Having said that, automating a mechanic (basically something else pressing the buttons for you) is cheating. Something that XIVCombo surely isn't, since at the end of the day you still need to press the buttons that the plug-in swaps out for you.

**Comment by UmbraVenus** [comment]
@lucianhatlemauri01 i agree with u in the ast card play, which is why I think it's not cheating since it's just convenience for controller play instead of optimizing, which player can opt in or opt out, the reason I chose enmity is because I believe it would be easier to program that way. 

Also sorry for not making myself clear, we do press the buttons, draw, and replay and minor arcana, just to change the function of the button slightly. It's no different from the ast play macro on PC really.

**Comment by lucianhatlemauri01** [comment]
If it's like what we have on pc, so basically Draw gets replaced with Play. Then it's absolutely fine, but the moment you ask a code or plug-in to find the best person suited for the card for you, then in my opinion it's borderline cheating if not cheating in full.
The difficulty of AST is exactly that, people spend hours optimizing their cards, learning everyone else's rotation to know who is more suitable for a card in that moment. To automate that, like your first (and perhaps second as well) post implies, means that you're throwing away a lot of hard-work done by other players.

On the other hand, I suggest you use XIV Combo like it is now and also use JobBars to see who is in full burst and who isn't. There you will know who to give your card to.

**Comment by attickdoor** [comment]
So you want a bot. No.
