### ISSUE TITLE
Monk Suggestion

### ISSUE THREAD

**Issue by Nikslg** [attickdoor/XIVComboPlugin#66]
Since it's hard to think of a "1 key combo" for Monk.
Perhaps an alternative would be grouping by flank and rear?
Bootshine => True Strike => Demolish
Dragon Kick => Twin Snakes => Snap Punch

They would change based on stance, not the move used before it.
I am not sure if it's possible, but could it be a good way of making Monk simplier?

**Comment by Carighan** [comment]
I was thinking the same the other day, and I feel I might as well code it up and send in a merge request.

I would also agree that "Rear" vs "Flank" (vs "AoE", which we already have) would be the easiest, but I'd be interested in whether others think a "Damage" (Bootshine ->True Strike -> Snap Punch) vs "Utility" (Dragon Kick -> Twin Snakes -> Demolish) would be something others prefer. It'd be weird due to the constant "dancing", but we already have that anyways.

That being said, I wonder how this'll interact with the various "ignore stance requirement" modifiers we have. I'm still a lowbie-MNK, so I cannot really comment on it. Does someone have input on this?

**Comment by Nikslg** [comment]
> I was thinking the same the other day, and I feel I might as well code it up and send in a merge request.
> 
> I would also agree that "Rear" vs "Flank" (vs "AoE", which we already have) would be the easiest, but I'd be interested in whether others think a "Damage" (Bootshine ->True Strike -> Snap Punch) vs "Utility" (Dragon Kick -> Twin Snakes -> Demolish) would be something others prefer. It'd be weird due to the constant "dancing", but we already have that anyways.
> 
> That being said, I wonder how this'll interact with the various "ignore stance requirement" modifiers we have. I'm still a lowbie-MNK, so I cannot really comment on it. Does someone have input on this?

Can you teach me the way to do it?
I'd like to experiment with these.
Always loved chaining spells in other games.

**Comment by SidAbhi** [comment]
Yep I was levelling up MNK today and thought the same thing. It seems complex at first, but it's actually still possible to make a combo action from MNK's weaponskill

**Comment by attickdoor** [comment]
This doesn't work. What will you do during Perfect Balance? This requires the plugin to know what buttons you want to push during PB, and railroads you into my choice for that rotation, regardless of any other fight context. Similarly, what do you do with the new Form Shift? It would have to pick a button, and any amount of intelligence in this process ("pick Twin Snakes if the buff is down/about to expire") goes straight into botting territory.

Monk is not getting single-target combos until these parts of its rotation change.
