### ISSUE TITLE
[MNK] More Combos

### ISSUE THREAD

**Issue by Deorigosa** [attickdoor/XIVComboPlugin#97]
Would be nice to have 2 more MNK combos

1) Raw damage combo
    `Bootshine -> True Strike -> Snap Punch`
2) Buff/Debuff combo
    `Dragon Kick -> Twin Adder -> Demolish`

DRG already has similar treatment, why not MNK?

**Comment by lovelydumpling** [comment]
Perfect Balance and Form Shift require access to all skills at the same time, removing the ability to save hotbar space. See #66.

**Comment by ParasiteXX** [comment]
A suggestion now that Endwalker removed positional requirements for most of the actions. Mainly the Opo-opo and Raptor stance actions.
Have Dragon Kick go into Boot Shine if Leaden Fist is up. 

Another suggestion is True Strike changes into Twin Snakes if Disciplined Fist buff isn't up or is about to run out.

One more suggestion is for Perfect Balance to turn into Masterful Blitz when Beast gauge is filled up.

**Comment by arrek85** [comment]
For the conditional combo (DK, TA, Demo) it doesn't make a ton of sense because these are situational by nature and as listed in 66 the botting argument remains valid.
For the Damage combo tho, I think it may need to be re-addressed. Under Formless you go Bootshine anyways which is the starting point of the combo, under PB you go Snap Punch. It's not even a decision as triple Snaps is 935 overall Pot and Triple Bootshine with one Crit is still only 835. Even if not wanting to do a lock down as Snap Punch under Perfect Balance effect the combo still saves space as 1 Combo Button and 1 Utility Snap Punch. Even one more free space on my controller setup would be nice.

Besides all that,
Perfect Balance > Masterful Blitz would be nice

**Comment by attickdoor** [comment]
no.
